### ISSUE TITLE
Chinese display

### ISSUE THREAD

**Issue by Tarocch1** [filhocf/roundcubemail-skin-chameleon#1]
I made some changes to display Chinese better:

styles.less 247:
``` css
top: -3px;
```

styles.less 539:
``` css
.toolbar a.button {
	font-weight: normal;
	text-transform: none;
	height: 15px;	/*new line*/
}
```

:)
